name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Semantic release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        shell: bash
        run: |
            npx semantic-release

